---
#The zones_id variable supports a list of zones. e.g.: "zones_id": [1234,5678,9012]
- name: "Purge CF Zones"
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ item }}/purge_cache"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ cloudflare_api_token }}"
    body_format: json
    body: 
      purge_everything: true
  register: purge_result
  no_log: true
  with_items:
    - "{{ zones_id }}"
